version: '3.8'

services:
  app:
    container_name: app-faf
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres-shared:5432/api-transferegov
      - REDIS_URL=redis://redis-shared:6379/2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-faf.rule=Host(`api.kingdomsys.com`)&&PathPrefix(`/api-faf`)"
      - "traefik.http.routers.api-faf.entrypoints=websecure"
      - "traefik.http.routers.api-faf.tls=true"
      - "traefik.http.routers.api-faf.tls.certresolver=letsencrypt"
      - "traefik.http.services.api-faf.loadbalancer.server.port=8000"
       # Adicione esta configuração para WebSockets
      - "traefik.http.routers.api-faf-ws.rule=Host(`api.kingdomsys.com`) && PathPrefix(`/api-faf/ws`)"
      - "traefik.http.routers.api-faf-ws.entrypoints=websecure"
      - "traefik.http.routers.api-faf-ws.tls=true"
      - "traefik.http.routers.api-faf-ws.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api-faf-ws.service=api-faf"

networks:
  default:
    name: web-apps
    external: true
